mysite/buisness_card/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path("", views.Main_Page_view.as_view(), name ="main_page"),
    path("contact/", views.Contact_view.as_view(), name ="contact"),
    path("portfolio/", views.Project_view.as_view(), name="portfolio"),
    path("reviews/", views.Reviews_view.as_view(), name="review_list"),
    path("faq/", views.Question_Answer.as_view(), name="question_answer"),
    path("add-review/", views.Add_review_view.as_view(), name="add_review"),
    path("<slug:slug>/", views.Project_Detail.as_view(), name ="project_detail"),
    path('accounts/login/', LoginView.as_view(), name='login'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin', admin.site.urls),
    path('', include("buisness_card.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('demos/', include('python_code.urls')),
    path('registration/', include('registration.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

mysite/python_code/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("list/", views.Demos_view.as_view(), name="demos_list"),
    path('run_scraping/', views.run_scraping, name='run_scraping'),
    path('run_calculator/', views.run_calculator, name='run_calculator'),
    path('run_AI_bot/', views.run_ai_bot, name='run_ai_bot'),
]

mysite/registration/urls.py
from .views import *
from django.urls import path

urlpatterns = [
    # ...
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', registration_view, name='register'),

]

mysite/buisness_card/models.py
from django.db import models
from datetime import date

from django.urls import reverse

class Project(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField("Text Area")
    date = models.DateField("Project Date", default=date.today)
    image = models.ImageField("Image", upload_to="projects", blank=True, null=True)
    url = models.SlugField(max_length=100, unique=True, null=True)
    draft = models.BooleanField(default=False)
    position = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('project_detail', kwargs={"slug": self.url})

class ProjectImages(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="project_picture/")
    movie = models.ForeignKey(Project, on_delete=models.CASCADE) # Project

    def __str__(self):
        return self.title

class QuestionsAnswer(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField("Text Area")
    position = models.IntegerField(default=0)

class Reviews(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=50)
    text = models.TextField("Text Area")

mysite/buisness_card/forms.py
from django import forms
from .models import Reviews

class AddReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['email', 'name', 'text']
        widgets = {
            'email': forms.TextInput(attrs={'readonly': 'readonly'}),
            'name': forms.TextInput(attrs={'readonly': 'readonly'})
        }

mysite/buisness_card/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.base import View
from .models import Project, QuestionsAnswer, Reviews
from .forms import AddReviewForm
from django.contrib import messages
from django.http import HttpResponseNotFound


class Project_view(ListView):
    model = Project
    queryset = Project.objects.filter(draft=False).order_by("-id")
    template_name = "posts/projects_list.html"

    # def get(self, request):
    #     projects = Project.objects.all()
    #     return render(request, "posts/projects_list.html", {"project_list":projects})

class Project_Detail(DetailView):
    model = Project
    slug_field = "url"
    template_name =  "posts/project_info.html"

class Question_Answer(View):
    def get(self, request):
        quest_answr = QuestionsAnswer.objects.order_by("position","-id")
        return render(request, "posts/FAQ.html", {"question_answer":quest_answr})

class Reviews_view(View):
    def get(self, request):
        reviews = Reviews.objects.order_by("-id")
        return render(request, "posts/reviews.html", {"reviews":reviews})

class Add_review_view(View):
    def get(self, request):
        if not request.user.is_authenticated:
            messages.error(request, 'You must be logged in to add a review.')
            return redirect('login')
        form = AddReviewForm()
        context = {'form': form}
        return render(request, "posts/form_add_review.html", context)

    def post(self, request):
        form = AddReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("review_list")
        return render(request, "posts/form_add_review.html", {"form": form})

class Contact_view(View):
    def get(self, request):
        return render(request, "posts/contact.html")


class Main_Page_view(View):
    def get(self, request):
        content_one = Project.objects.filter(draft=False).order_by("-position", "-id")[:4]
        content_two = QuestionsAnswer.objects.order_by("-position","-id")[:3]
        content_three = Reviews.objects.order_by("-id")[:3]
        return render(request, "posts/main_page.html", {"content_one":content_one,"content_two":content_two,"content_three":content_three })


def Page_not_found(request, exception):
    return HttpResponseNotFound(render(request, 'posts/page_not_found.html'))

mysite/python_code/views.py
from django.shortcuts import render
from django.views import View
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.views.generic import ListView

from . import scraping
from .ask_ai import ask_question
from .calculator import calculator_res


@csrf_exempt
def run_scraping(request):
    query, result_conent, list_of_site = None, None, None
    if request.method == 'POST':
        input_text = request.POST.get('input_text', '')
        query, result_conent, list_of_site = scraping.run_scraping(input_text)

    return render(request, 'demos/run_scraping.html',
                  {"query": query, "result_conent": result_conent, "list_of_site": list_of_site})


@csrf_exempt
def run_calculator(request):
    if request.method == 'POST':
        num_one = float(request.POST.get('num_one'))
        num_two = float(request.POST.get('num_two'))
        operation = request.POST.get('operation')
        result = calculator_res(num_one, num_two, operation)
        context = {
            'result': result
        }
        return render(request, 'demos/run_calculator.html', context)
    else:
        return render(request, 'demos/run_calculator.html')

@csrf_exempt
def run_ai_bot(request):
    result= None
    if request.method == 'POST':
        input_text = request.POST.get('input_text', '')
        result = ask_question(input_text)

    return render(request, 'demos/run_askAI.html',
                  {"result":result})



class Demos_view(View):
    def get(self, request):
        return render(request, "demos/list.html")

mysite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static  'admin/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'admin/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=ABeeZee&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich&amp;display=swap">
    <link rel="stylesheet" href="{% static 'admin/fonts/fontawesome-all.min.css'%}">
    {% block head %}

    {% endblock head %}

</head>
<body>
{% include 'include/header.html' %}
{% block content %}


{% endblock content %}
{% include 'include/footer.html' %}
</body>
</html>

mysite/templates/demos/list.html
{%extends 'posts/base.html'%}
{%load static%}

{% block head%}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Demos</title>
    <link rel="stylesheet" href="{% static 'admin/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich&amp;display=swap">
</head>
{% endblock head%}
{%block info%}
<body style="font-family: Aldrich, sans-serif;">
    <h1 style="text-align: center;margin-top: 5px;margin-bottom: 15px;">Demos</h1>
    <div class="col" style="margin-left: 6%;margin-right: 6%;text-align: center;">
        <p>On the demo page, you can explore some of the Python projects that I have worked on. Each project has been carefully crafted to demonstrate the power and versatility of Python programming, and to showcase the high-quality work that I can deliver. So, if you're curious about what I can do, I invite you to take a look at the demos and try them out for yourself!</p>
    </div>
    <div class="col" style="margin-right: 5%;margin-left: 5%;border-top-left-radius: 17px;border-top-right-radius: 17px;border-bottom-right-radius: 17px;border-bottom-left-radius: 17px;margin-top: 15px;border-style: solid;border-color: rgb(108,120,133);border-top-width: 4px;border-right-width: 1.5px;border-bottom-style: solid;border-bottom-color: rgb(108,120,133);border-left-width: 1.5px;">
        <div style="margin-left: 10px;">
            <h3 style="text-align: left;margin-top: 10px;">Extract Information with Ease: Try Out My Google Web Scraping Demo</h3>
            <p style="margin-bottom: 15px;margin-right: 5%;">The "Scrape some text from Google" demo showcases my web scraping skills by extracting text from Google search results using Python. It demonstrates my ability to utilize Python libraries such as BeautifulSoup and requests to automate the scraping process and extract data from websites.</p><a href="{% url 'run_scraping' %}" style="color: rgb(134,144,157);">Try it&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-up-right">
                    <path fill-rule="evenodd" d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0v-6z"></path>
                </svg></a>
        </div>
    </div>
    <div class="col" style="margin-right: 5%;margin-left: 5%;border-top-left-radius: 17px;border-top-right-radius: 17px;border-bottom-right-radius: 17px;border-bottom-left-radius: 17px;margin-top: 15px;border-style: solid;border-color: rgb(108,120,133);border-top-width: 4px;border-right-width: 1.5px;border-bottom-style: solid;border-bottom-color: rgb(108,120,133);border-left-width: 1.5px;">
        <div style="margin-left: 10px;">
            <h3 style="text-align: left;margin-top: 10px;">Perform Quick Calculations: Check Out My Simple Calculator Demo</h3>
            <p style="margin-bottom: 10px;">My "Simple Calculator" demo highlights my proficiency in creating Python programs for basic arithmetic operations. With a user-friendly interface and intuitive functionality, it can perform quick calculations for addition, subtraction, multiplication, and division. Try it out to see how my programming skills can assist you in streamlining your mathematical tasks.</p><a href="{% url 'run_calculator' %}" style="color: rgb(134,144,157);">Try it&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-up-right">
                    <path fill-rule="evenodd" d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0v-6z"></path>
                </svg></a>
        </div>
    </div>
    <div class="col" style="margin-right: 5%;margin-left: 5%;border-top-left-radius: 17px;border-top-right-radius: 17px;border-bottom-right-radius: 17px;border-bottom-left-radius: 17px;margin-top: 15px;border-style: solid;border-color: rgb(108,120,133);border-top-width: 4px;border-right-width: 1.5px;border-bottom-style: solid;border-bottom-color: rgb(108,120,133);border-left-width: 1.5px;">
        <div style="margin-left: 10px;">
            <h3 style="text-align: left;margin-top: 10px;">Get Instant Answers: Experience My AI Chatbot Demo</h3>
            <p style="margin-bottom: 10px;">My demo showcases my proficiency in Natural Language Processing and Artificial Intelligence, enabling me to create programs that can answer questions posed in natural language. With the use of machine learning algorithms and Python, I can develop reliable solutions to handle complex queries and provide relevant information promptly. Let me show you how my programming skills can elevate your user experience.</p><a href="{% url 'run_ai_bot' %}" style="color: rgb(134,144,157);">Try it&nbsp;<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-up-right">
                    <path fill-rule="evenodd" d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0v-6z"></path>
                </svg></a>
        </div>
    </div>
    <script src="{% static '/admin/js/bootstrap.min.js'%}"></script>
</body>

{%endblock info%}

mysite/templates/demos/run_askAI.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>Run AI bot | Ask question to AI</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich&amp;display=swap">
</head>
{%endblock%}

{% block content %}
<section style="height: auto;margin-top: 50px;">

	<h1>Run AI Bot</h1>
	{% if message %}
	<p>{{ message }}</p>
	{% endif %}
	<form method="POST" id="ai-form">
		{% csrf_token %}
		<input type="text" name="input_text" placeholder="Enter Text">
		<button type="submit">Run AI</button>
	</form>

	<h2>{{result}}</h2>
	<p></p>


</section>
{% endblock %}

<script>
	    var form = document.getElementById("ai-form");
	    form.addEventListener("submit", function(event) {
	        event.preventDefault();
	        var input_text = document.getElementsByName("input_text")[0].value;
	        var xhr = new XMLHttpRequest();
	        xhr.onreadystatechange = function() {
	            if (xhr.readyState === XMLHttpRequest.DONE) {
	                document.getElementById("loading").style.display = "none";
	                document.getElementById("result").style.display = "block";
	                if (xhr.status === 200) {
	                    var response = JSON.parse(xhr.responseText);
	                    document.getElementsByName("input_text")[0].value = "";
	                    document.getElementById("result").getElementsByTagName("p")[0].innerHTML = response.result;
	                } else {
	                    console.log("Error: " + xhr.status);
	                }
	            } else {
	                document.getElementById("loading").style.display = "block";
	                document.getElementById("result").style.display = "none";
	            }
	        };
	        xhr.open("POST", "/run_ai_bot/");
	        xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
	        xhr.send("input_text=" + encodeURIComponent(input_text));
	    });

</script>

mysite/templates/demos/run_calculator.html
{% extends 'base.html' %}

{% block head %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>Calculator | Solve with a calculator</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich&amp;display=swap">
</head>
{%endblock%}

{% block content %}
<section style="height: auto;margin-top: 50px;">

	<h1>Run Calculator</h1>
	{% if message %}
	<p>{{ message }}</p>
	{% endif %}

	<form method="post">
		{% csrf_token %}
		<label for="num_one">Первое число:</label>
		<input type="number" name="num_one" id="num_one" required>
		<br>
		<label for="num_two">Второе число:</label>
		<input type="number" name="num_two" id="num_two" required>
		<br>
		<label for="operation">Операция:</label>
		<select name="operation" id="operation" required>
			<option value="+">Сложение</option>
			<option value="-">Вычитание</option>
			<option value="*">Умножение</option>
			<option value="/">Деление</option>
		</select>
		<br>
		<button type="submit">Вычислить</button>
	</form>
	{% if result %}
	<p>Результат: {{ result }}</p>
	{% endif %}
</section>
{% endblock %}

mysite/templates/demos/run_scraping.html
{% extends 'base.html' %}

{% block head %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>Web Scraper | Collect information with the help of a scraper</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich&amp;display=swap">
</head>
{%endblock%}

{% block content %}
<section style="height: auto;margin-top: 50px;">

	<h1>Run Scraping</h1>
	{% if message %}
	<p>{{ message }}</p>
	{% endif %}
	<form method="POST">
		{% csrf_token %}
		<input type="text" name="input_text" placeholder="Enter Text">
		<button type="submit">Run Scraping</button>
	</form>
	{% if query %}
	<h1>Search Results for "{{ query }}"</h1>
	<p>{{ result_conent }}</p>
	{% if list_of_site %}
	<h2>List of Sites</h2>
	<ul>
		{% for title, link in list_of_site.items %}
		<li><a href="{{ link }}">{{ title }}</a></li>
		{% endfor %}
	</ul>
	{% else %}
	<p>No results found.</p>
	{% endif %}
	{% endif %}
</section>
{% endblock %}

mysite/templates/include/header.html
{% load static %}
<nav class="navbar navbar-light navbar-expand-md d-md-flex justify-content-md-center"
     style="background: rgba(255,255,255,0.48);font-family: Aldrich, sans-serif;font-size: 18px;border-radius: 1px;border-bottom: 1px solid rgb(0,0,0);">
	{% with request.resolver_match.url_name as url_name %}
	<div class="container"><a class="navbar-brand" href="{% url 'main_page' %}">Main page</a>
		<button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span
				class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse flex-fill justify-content-md-center justify-content-xxl-center"
		     id="navcol-1">
			<ul class="navbar-nav ms-ws/assets/bootstrap/js/bootstrapauto">
				<li class="nav-item"><a class="nav-link {% if url_name == 'question_answer' %}active{% endif %}"
				                        href="{% url 'question_answer' %}">FAQ</a></li>
				<li class="nav-item"><a class="nav-link {% if url_name == 'review_list' %}active{% endif %}"
				                        href="{% url 'review_list' %}">Reviews</a></li>
				<li class="nav-item"><a class="nav-link {% if url_name == 'demos_list' %}active{% endif %}"
				                        href="{% url 'demos_list' %}">Demo</a></li>
				<li class="nav-item"><a class="nav-link {% if url_name == 'add_review' %}active{% endif %}"
				                        href="{% url 'add_review' %}">Add review</a></li>
				<li class="nav-item"><a class="nav-link {% if url_name == 'portfolio' %}active{% endif %}"
				                        href="{% url 'portfolio' %}">Portfolio</a></li>
				<li class="nav-item"><a class="nav-link {% if url_name == 'contact' %}active{% endif %}"
				                        href="{% url 'contact' %}">Contact</a></li>
			</ul>
			{% if user.is_authenticated %}
			<ul class="navbar-nav d-xxl-flex ms-auto align-items-xxl-center">
				<li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
				<li class="nav-item"><a class="nav-link" href="#">{{ user.username }}!</a></li>
				<li class="nav-item"></li>

				{% else %}
				<ul class="navbar-nav d-xxl-flex ms-auto align-items-xxl-center">
					<li class="nav-item"><a class="nav-link active" href="{% url 'login' %}">Log in</a></li>
					<li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Regestration</a></li>
					<li class="nav-item"></li>
				</ul>
				{% endif %}
			</ul>
		</div>

	</div>
	{% endwith %}
	<script src="{%static 'admin/js/bootstrap.min.js'%}"></script>
	<script src="{%static 'admin/js/aos.min.js'%}"></script>
	<script src="{%static 'admin/js/bs-init.js'%}"></script>
</nav>

mysite/templates/posts/FAQ.html
{%extends 'posts/base.html'%}
{% load static %}

{% block head %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>FAQ</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich&amp;display=swap">
</head>
{% endblock %}

{% block content%}
<body style="font-family: Aldrich, sans-serif;">
<section style="margin-right: 2%;margin-left: 2%;">
	<h1 style="text-align: center; margin-top: 3px;">Frequently Asked Questions</h1>
	<div class="container">
		<div class="row" style="padding-top: 10px;">
			{% for question in question_answer%}
			<div class="col-md-6"
			     style="border-top-left-radius: 17px;border-top-right-radius: 17px;border-bottom-right-radius: 17px;border-bottom-left-radius: 17px;margin-top: 5px;margin-bottom: 5px;border-style: solid;border-color: rgb(108,120,133);border-top-width: 4px;border-top-color: rgb(106,119,132);border-right-width: 1.5px;border-left-width: 1.5px;">
				<h2 class="text-center" style="margin-top: 3px;">{{question.title}}</h2>
				<p>{{question.description|safe}}</p>
			</div>
			{% endfor %}
		</div>
	</div>
</section>
<script src="{% static 'admin/js/bootstrap.min.js'%}"></script>
</body>

{% endblock %}

mysite/templates/posts/base.html
{% extends 'base.html' %}
{% block head%}
{% endblock head%}

{% block content%}

{%block info%}
{%endblock info%}

{% endblock content%}

mysite/templates/posts/page_not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>404</title>
</head>
<body>

</body>
</html>

mysite/templates/posts/project_info.html
{%extends 'posts/base.html'%}
{% load static %}

{% block head %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>{{project.title}}</title>
	<link rel="stylesheet" href="{% static 'admin/css/bootstrap.min.css'%}">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich&amp;display=swap">
</head>
{% endblock %}

{% block content%}
<body style="font-family: Aldrich, sans-serif;">
<div class="col" style="margin-right: 3%;margin-left: 3%;margin-top: 20px;">
	<div style="border-top-left-radius: 17px;border-bottom-right-radius: 17px;border-top-right-radius: 17px;border-bottom-left-radius: 17px;border-style: solid;border-color: rgb(108,120,133);border-top-width: 4px;">
		<h1 style="text-align: center;margin-top: 15px;"><span style="color: rgb(0, 0, 0);">{{project.title}}</span>
		</h1>
		<div class="container" style="margin-top: 20px;margin-bottom: 10px;">
			<div class="row">
				<div class="col-md-6" style="margin-top: 10px;">
					<div class="carousel slide" data-bs-ride="false" id="carousel-1">
						<div class="carousel-inner">
							{% for img in project.projectimages_set.all %}
							<div class="carousel-item active"><img class="w-100 d-block" src="/media/{{img.image}}"
							                                       alt="{{img.description}}"
							                                       style="border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-right-radius: 15px;border-bottom-left-radius: 15px;">
							</div>
							{% endfor %}

						</div>
						<div><a class="carousel-control-prev" href="#carousel-1" role="button"
						        data-bs-slide="prev"><span class="carousel-control-prev-icon"></span><span
								class="visually-hidden">Previous</span></a><a class="carousel-control-next"
						                                                      href="#carousel-1" role="button"
						                                                      data-bs-slide="next"><span
								class="carousel-control-next-icon"></span><span class="visually-hidden">Next</span></a>
						</div>
						{% if project.projectimages_set.exists %}
						<ol class="carousel-indicators">
							{% for img in project.projectimages_set.all %}
							<li data-bs-target="#carousel-1" data-bs-slide-to="{{ forloop.counter0 }}"
							    class="{% if forloop.first %}active{% endif %}"></li>
							{% endfor %}
						</ol>
						{% else %}
						<img class="w-100 d-block" src="{% static 'admin/img/Coming-Soon-Text-PNG-HD-Quality.png'%}"
						     style="border-top-right-radius: 15px;border-top-left-radius: 15px;border-bottom-right-radius: 15px;border-bottom-left-radius: 15px;">
						{% endif %}

					</div>
				</div>
				<div class="col-md-6" style="margin-top: 10px;">
					<p>{{project.text|safe}}</p>
					<p><span style="color: rgb(0, 0, 0);">{{project.date}}</span></p>
				</div>
			</div>
		</div>
		<div class="col" style="margin-bottom: 20px;text-align: center;">
			<a href="{% url 'portfolio' %}">
				<button class="btn btn-primary" type="button" style="background: rgb(135,145,160);">Back to list
				</button>
			</a>
		</div>
	</div>
</div>
<script src="{% static 'admin/js/bootstrap.min.js'%}"></script>
</body>
{%endblock%}

mysite/templates/posts/projects_list.html
{%extends 'posts/base.html'%}
{% load static %}
{% block head %}

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
	<title>Portfolio | All my projects</title>
	<link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Aldrich&amp;display=swap">
</head>
{% endblock %}

{% block content %}
<body style="font-family: Aldrich, sans-serif;">
<h1 style="text-align: center;">My projects list.</h1>
<div class="col" style="margin-right: 5%;margin-left: 5%;text-align: center;">
	<p style="margin-top: 20px;">My portfolio showcases my Python programming work, including web scraping, automation,
		and Django web development. I can assist you in collecting, analyzing, and extracting insights from website
		data, streamlining workflows, reducing errors, and creating user-friendly web applications. Let me know how I
		can help with your Python programming needs.</div>
{% for project in project_list%}
<div style="margin-right: 3%;margin-left: 3%;border-top-left-radius: 17px;border-top-right-radius: 17px;border-bottom-right-radius: 17px;border-bottom-left-radius: 17px;margin-top: 10px;border-style: solid;border-color: rgb(108,120,133);border-top-width: 4px;border-right-width: 1.5px;border-left-width: 1.5px;">
	<div class="col" style="margin-top: 5px;margin-left: 2%;margin-right: 2%;margin-bottom: 13px;">
		<h2><span style="color: rgb(0, 0, 0);">{{project.title}}</span></h2>
		<p>{{project.text|safe|slice:":400"}}
			...</p>
		<a href="{{ project.get_absolute_url }}">
			<button class="btn btn-primary" type="button" style="background: rgb(135,145,160);">View more</button>
		</a>

	</div>
</div>
{% endfor %}
<script src="{% static 'admin/js/bootstrap.min.js'%}"></script>
</body>
{%endblock%}